spring.application.name=Skill8-JPQL-Queries
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/product_db
spring.datasource.username=root
spring.datasource.password=Mysql@32060

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true