spring.datasource.url=jdbc:mysql://localhost:3306/s53
spring.datasource.username=root
spring.datasource.password=Indra@2574

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082